<a href="https://colab.research.google.com/github/Lakshay12009/python-series/blob/main/EDA_RECAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#step1: Load important Module

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')
print('All Module Loaded Successfully!!')

All Module Loaded Successfully!!

Step2: Load Dataset

In [7]:
url = 'https://gist.githubusercontent.com/nnbphuong/38db511db14542f3ba9ef16e69d3814c/raw/3a77ff9d97c504d3ec3210b12fde7242b8c6ab63/Superstore.csv'
df = pd.read_csv(url)
df.sample(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5788,5789,CA-2018-115070,2018-04-10,2018-04-14,Second Class,MG-18205,Mitch Gastineau,Corporate,United States,Jacksonville,...,32216.0,South,FUR-FU-10003829,Furniture,Furnishings,Stackable Trays,12.320,5,0.2,1.8480
7532,7533,CA-2017-107146,2017-06-17,2017-06-19,First Class,LC-16885,Lena Creighton,Consumer,United States,Longmont,...,80501.0,West,FUR-CH-10004853,Furniture,Chairs,"Global Manager's Adjustable Task Chair, Storm",483.136,4,0.2,54.3528

Step3 : Exploratory Data Analysis (EDA)

In [9]:
# Shape of the datset
df.shape

#This shows: 9K+ Records and 21 columns

(9994, 21)

In [10]:
#size of the datset
df.size

#This shows: total elements in a dataset

209874

In [11]:
# To check head: by default it gives 5 records
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

In [12]:
# To check tail: by default it gives 5 records
df.tail(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9993,9994,CA-2018-119914,2018-05-04,2018-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [13]:
# to check all column info
# It check nonnull count: means: how much data is not null
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9983 non-null   float64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

In [15]:
# To check null records count
# If all values are Zero which means
# no null; data found
# Postalcode: 11: means: 11 rows found null
df.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [16]:
# To describe the dataset
# It gives Numerical datasets stats info
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9983.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55245.233297,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32038.715955,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,57103.000000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [17]:
# To check categorical data describe
# Categorical means: textual data info
df.describe(include = 'object')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,1236,1334,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2018-100111,2017-09-05,2016-12-16,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,38,35,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48

In [18]:
# To check correlation b/w numerical features
df.corr(numeric_only= True)

# The range of corr: (-1 to 1)
# -1: One feature is going up and other is going down
# +1: Both going up
# 0: No correlation

               Row ID  Postal Code     Sales  Quantity  Discount    Profit
Row ID       1.000000     0.011644 -0.001359 -0.004016  0.013480  0.012497
Postal Code  0.011644     1.000000 -0.022346  0.013376  0.057243 -0.028751
Sales       -0.001359    -0.022346  1.000000  0.200795 -0.028190  0.479064
Quantity    -0.004016     0.013376  0.200795  1.000000  0.008623  0.066253
Discount     0.013480     0.057243 -0.028190  0.008623  1.000000 -0.219487
Profit       0.012497    -0.028751  0.479064  0.066253 -0.219487  1.000000